# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/caddy/certs:/etc/caddy/certs
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      XDEBUG_MODE: ${XDEBUG_MODE:-coverage}
      AUTO_HTTPS: "off"
      #      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
  #    tty: true

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  # messenger:
  #   build:
  #     context: .
  #     target: frankenphp_dev
  #   volumes:
  #     - ./:/app
  #     - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
