# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
#      APP_SECRET: ${APP_SECRET}
#      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
#      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    volumes:
      - caddy_data:/data
      - caddy_config:/config